---
- name: Upgrade IOS-XE
  hosts: switches
  gather_facts: no
  vars_prompt:
    - name: ansible_user
      prompt: Username
      private: false
    - name: ansible_password
      prompt: Password

  vars:
    new_version: 17.06.04
    new_file: "cat9k_lite_iosxe.{{ new_version }}.SPA.bin"
    tftp_ip: 10.2.225.71

  tasks:
    - name: Gather facts
      cisco.ios.ios_facts:
        gather_subset: hardware
      register: facts_output

    - name: print output
      debug:
        msg: "Current Version is {{ facts_output['ansible_facts']['ansible_net_version'] }}"

    - name: Save the Config
      cisco.ios.ios_command:
        commands:
          - command: "copy running-config startup-config"
            prompt: 'Destination filename \[startup-config\]\?'
            answer: "\r"
      register: save_config

    - name: Save config output
      debug:
        msg: "{{ save_config }}"

    - name: Start the Upgrade Process
      block:
        - name: Check for old files and remove them if found
          cisco.ios.ios_command:
            commands:
              - command: "install remove inactive"
                prompt:
                  - 'Do you want to remove the above files\? \[y/n\]'
                answer:
                  - "y"
          register: install_remove_output
          vars:
            ansible_command_timeout: 600

        - name: Display install_remove output and result
          debug:
            msg: "{{ 'No old files found. Nothing to clean.' if 'SUCCESS: No extra package or provisioning files found on media' in install_remove_output.stdout[0] else 'Old files removed successfully.' }}"

        - name: Copy IOS image via TFTP
          cisco.ios.ios_command:
            commands:
              - command: "copy tftp://{{ tftp_ip }}/{{ new_file }} flash:{{ new_file }}"
                prompt:
                  - "Destination filename [{{ new_file }}]?"
                answer:
                  - "\r"
          vars:
            ansible_command_timeout: 900

        - name: Install and activate new IOS image
          cisco.ios.ios_command:
            commands:
              - command: "install add file flash:{{ new_file }} activate commit"
                prompt:
                  - 'This operation may require a reload of the system. Do you want to proceed\? \[y/n\]'
                answer:
                  - "y"
          register: install_activate_output
          vars:
            ansible_command_timeout: 1200

        - debug:
            var: install_activate_output.stdout_lines

        - name: Wait for switch to reboot and become reachable
          wait_for_connection:
            delay: 180
            sleep: 60
            timeout: 900

        - name: Gather new facts
          cisco.ios.ios_facts:
            gather_subset: hardware
          register: facts_output_new

        - name: New Version
          debug:
            msg: "New Version is {{ facts_output_new['ansible_facts']['ansible_net_version'] }}, Upgrade Successfully Completed"
          when: new_version == facts_output_new['ansible_facts']['ansible_net_version']

      when: new_version != facts_output['ansible_facts']['ansible_net_version']
